# Generated by Django 5.0.2 on 2024-02-19 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('template', models.CharField(max_length=120)),
                ('parentElem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.node')),
            ],
        ),
        migrations.CreateModel(
            name='MenusToNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.menu')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.node')),
            ],
        ),
    ]
