# Generated by Django 5.0.2 on 2024-02-20 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_node_parentelem'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.menu'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MenusToNodes',
        ),
    ]
