# Generated by Django 5.0.2 on 2024-02-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_node_menu_delete_menustonodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='template',
            new_name='url',
        ),
    ]
